name: Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: get-npm-version
      id: package-version

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hsa24:${{ steps.package-version.outputs.current-version}}
